### ISSUE TITLE
Does not account for changing children

### ISSUE THREAD

**Issue by bitttttten** [davidcetinkaya/embla-carousel-react#10] opened 2019-11-14 13:17 UTC
It seems that after changing the amount of items in the carousel, the old settings are kept and you are not able to scroll to new items if they are added. Or if items are removed, then you are able to scroll to "ghost" items (spooky 👻).

(codesandbox seems to be a bit buggy, and is overwriting my previous saves.. so hopefully one of them at least showcases the issue!)

Increasing demo: https://codesandbox.io/s/embla-carousel-react-4oinz
Decreasing demo: https://codesandbox.io/s/embla-carousel-react-9relu

In the demo, a new item is added every second. You can see that items are added to the carousel, but it's not possible to scroll to any item above 1.

Currently, my workaround is calling `embla.updateOptions` whenever the children change, or in the demo, I could do it when `amount` changes. It would be nice to have this implementation detail inside the library so that the code can still be written declarativity.

```js
  useEffect(() => {
    embla.changeOptions(emblaOptions);
  }, [children]);
```

Here is a demo with my above workaround: https://codesandbox.io/s/embla-carousel-react-qmmhs

**Comment by davidcetinkaya** [comment] 2019-11-16 11:44
Hi @bitttttten,

Thank you for opening this issue. And wow! Ghost items 👻, and here I thought halloween was over 😅.

Jokes aside, thank you for providing clear showcases, it really helps. This is related to issue #9. It might come as a surprise but this is actually by design. And not in the sense that: Wow, so cool, a React component that doesn't recognize when its children count changes. But rather: What's the smallest possible React wrapper I can build for the Embla Carousel viewport and expose the Embla API, in order to leave the rest of the implementation up to the user?

I realize that: ` embla.changeOptions({})` isn't declarative at all. I've been thinking about exposing an API method that reads better. Like:

```javascript
embla.reInit()

// ...or

embla.lookForChanges()
```

What's your thoughts on this?

If we were to proceed with your suggestion it raises more questions than just the children count reactivity I think. The main question being: 

- Shouldn't the Embla React Component also update all Embla API methods (like `embla.canScrollPrev()`) when the children count changes?

I'm open to suggestions and would appreciate your thoughts on this.

Thanks in advance!
David

**Comment by bitttttten** [comment] 2019-11-18 16:28
I think exposing the API method is a great idea! And then in `embla-carousel-react` you could run this when children change.

> Shouldn't the Embla React Component also update all Embla API methods (like embla.canScrollPrev()) when the children count changes?

My vote is yes since it keeps it align with React's declarative API. It is "just like" if Embla was destroyed and recreated. Also exactly like when changing state on a component. I would expect to be reading any of the Embla methods and they would reflect or match the state of my component as it is.

**Comment by bitttttten** [comment] 2019-11-20 11:20
> We have a growing number of users for this package (based on the last months increase), and this change will be a breaking change for all of them.

That's a good point. When I wrote the issue, I was imagining it would be fixing a lot of bugs since if you wrote your embla-carousel-react component declaratively, and this was released in the core, it would only be making your UI more consistent. (I hope) most people write declarative UI for React so it wasn't imagining it being a breaking change. 

> Considering that, if we can come up with a nice draft I will add the label opinion wanted to gather additional user opinions.

Sounds fair!

> Bonus - Refactor the package to React Hooks.

Sounds interesting. It could also help with people sharing their own hooks, like a hook for autoplay, or something.

So I have a lil demo here: https://codesandbox.io/s/embla-carousel-react-lf5xj Don't look too much into it.. I had to remove all the plumbing inside `EmblaCarousel.js`, where you get the state from Embla and set it to the component. It's tricky! I wonder if using context would be better suited for this kind of thing.

I also appreciate the performance is not great.

Plus I also see an issue, if you drag and between slide 1 and 2 whilst it updates, it snaps back to where you snapped from. Not a great user experience!

I will keep thinking :)

**Comment by bitttttten** [comment] 2019-11-20 11:21
But I now do appreciate your comment that this is the most minimal wrapper to get it working inside React 😄

**Comment by bitttttten** [comment] 2019-11-20 13:12
Here is an example of what I imagine the declarative API looking like. I am also looking at docs like `react-spring` for the inspiration. 

This is basically pseudo code. I am sending in the children to `useEmbla`, so Embla knows to recreate itself which is not ideal. Plus it loses the previous state too. It's also not very performant :)

Although every time `useEmbla` is called, it will reinitialise as we discussed above.

It's just food for thought!

```js
const EmblaCarouselComponent = ({ children }) => {
  const emblaOptions = useMemo(() => ({ loop: false }), []);
  const { ref, embla } = useEmbla(children, emblaOptions);
  const scrollTo = index => embla.scrollTo(index)
  const scrollPrev = embla.scrollPrev
  const scrollNext = embla.scrollNext
  const scrollSnaps = embla.scrollSnapList()
  const prevBtnEnabled = embla.canScrollPrev()
  const nextBtnEnabled = embla.canScrollNext()
  const selectedIndex = embla.selectedScrollSnap()
  return (
    <div className="embla">
      <div className="embla__viewport" ref={ref} >
        <div className="embla__container">{children}</div>
      </div>
      <div className="embla__dots">
        {scrollSnaps.map((snap, index) => (
          <DotButton
            selected={index === selectedIndex}
            onClick={() => scrollTo(index)}
            key={index}
          />
        ))}
      </div>
      <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled} />
      <NextButton onClick={scrollNext} enabled={nextBtnEnabled} />
    </div>
  );
};
```

```js
export function useEmbla(items, options) {
  const [embla, setEmbla] = useState(null);
  const ref = useRef(null);

  useEffect(() => {
    const emblaCarousel = EmblaCarousel(ref.current, options);
    setEmbla(emblaCarousel);
    return () => {
      emblaCarousel.destroy();
    };
  }, [items, options]);

  return { ref, embla };
}
```

**Comment by davidcetinkaya** [comment] 2019-11-23 16:11
Hi @bitttttten.
Thank you for your input and your examples!

As you mention I don't want to hurt performance. Also, Embla's main purpose is to provide a low level carousel in contrast to its competitors that comes with everything out of the box. So I don't want it to do and decide too much for the end users. Having said that, I see your point about declarative code, and I'll look into this and get back to you when I've done so. I hope this is ok with you.

I'm currently working on **Embla v.3** because I have a couple of feature requests so it could take some time. 

👉 **In the meantime, if anyone have any input on this issue he/she is welcome to help out!**

Best,
David

**Comment by davidcetinkaya** [comment] 2019-12-18 13:05
Hello again,

I'm going to close this issue due to lack of interest. Feel free to reopen it if you think it should be prioritised.

Thank you!

**Closed by davidcetinkaya** 2019-12-18 13:05 UTC
Labels: feature request, help wanted, opinion wanted
